name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: unzip Phoen1xGUI-master.zip

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK 36
        run: sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Fix SDK path and remove invalid local aapt2 override
        run: |
          echo "sdk.dir=$ANDROID_HOME" > Phoen1xGUI-master/local.properties
          sed -i '/aapt2FromMavenOverride/d' Phoen1xGUI-master/gradle.properties
      - name: Grant execute permission
        run: chmod +x Phoen1xGUI-master/gradlew

      - name: Build APK
        run: cd Phoen1xGUI-master && ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: Phoen1xGUI-master/app/build/outputs/apk/debug/app-debug.apk
